version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: base64:3T9gzd3Icv889lzYlhQs4YmJhMHM8x0wRPaBku2Y1hk=
      APP_URL: http://localhost:9000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: alumni
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: p6df3v7zRbYCkAwbgsJUXaGwF4IwMfYqe0JwPUOXEGIQ2OAkoIkU0zumxfF4exCU
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alumni
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
